name: Mention Responder

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  respond-to-mentions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Respond to mentions
        run: python .github/scripts/respond_to_mentions.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
